# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
defaults: &defaults
  working_directory: ~/project/gitx-web
  docker:
  - image: circleci/node:latest

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Check files
          command: pwd & ls -la
      - persist_to_workspace:
          root: ~/project/gitx-web
          paths:
            - ./
  lint_commit_message:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project/gitx-web
      - run:
          name: Define environment variable with lastest commit's message
          command: |
              echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
              source $BASH_ENV
      - run:
          name: Check files
          command: pwd & ls -la
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project/gitx-web
      - run: yarn test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - lint_commit_message:
          requires:
            - prepare
      - test:
          requires:
            - prepare


